DROP TABLE TB_BLOB;
CREATE TABLE TB_BLOB
(
B_LOB BLOB
,ID INT NOT NULL
,DATABASENAME   VARCHAR(255 CHARS) CHARACTER SET UTF8
,INSTANCENAME  VARCHAR(255 CHARS) CHARACTER SET UTF8
,USERNAME      VARCHAR(255 CHARS) CHARACTER SET UTF8
,CREATETIME    TIMESTAMP(6)
,FDBVERSIONMAJOR    INT
,FDBVERSIONMINOR    INT
,FDBVERSIONBUGFIX   INT
,FDEPROVIDERNAME    VARCHAR(255 CHARS) CHARACTER SET UTF8
,FDEDESCRIPTION     VARCHAR(1024 CHARS) CHARACTER SET UTF8
,UID                VARCHAR(64 CHARS) CHARACTER SET UTF8
,PRIMARY KEY (ID)
);

